package app.commutenity.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class CommuteColors(
    val map: Color,
    val park: Color,
    val building: Color,
    val roadCasing: Color,
    val road: Color,
    val roadMinor: Color,
    val route: Color,
    val dash: Color,
    val label: Color,
    val ink: Color,
    val muted: Color,
    val faint: Color,
    val surface: Color,
    val handle: Color,
    val reason: Color,
    val reasonOn: Color,
    val sample: Color,
    val sampleOn: Color,
    val para: Color,
    val paraOn: Color,
    val pinA: Color,
    val pinAOn: Color,
    val pinB: Color,
    val pinBOn: Color,
    val connector: Color,
    val step: Color,
    val shadow: Color,
    val isDark: Boolean,
)

val LightColors = CommuteColors(
    map = Color(0xFFE3F1DF),
    park = Color(0xFF9ECC7D),
    building = Color(0xFFFCF9F1),
    roadCasing = Color(0xFFB3D1AD),
    road = Color(0xFFFCF9F1),
    roadMinor = Color(0xFFF5FAF0),
    route = Color(0xFF2D9E5A),
    dash = Color(0xFF6B665E),
    label = Color(0xFF4A735C),
    ink = Color(0xFF0D5636),
    muted = Color(0xFF4A735C),
    faint = Color(0xFF6B8573),
    surface = Color(0xFFFCF9F1),
    handle = Color(0xFFCCE0C7),
    reason = Color(0xFFFDBC28),
    reasonOn = Color(0xFF0D5636),
    sample = Color(0xFFE5F2E0),
    sampleOn = Color(0xFF4A735C),
    para = Color(0xFF0D5636),
    paraOn = Color(0xFFFCF9F1),
    pinA = Color(0xFFF06020),
    pinAOn = Color(0xFF0D5636),
    pinB = Color(0xFF0D5636),
    pinBOn = Color(0xFFFCF9F1),
    connector = Color(0xFF9EC7A8),
    step = Color(0xFF6BB375),
    shadow = Color(0x241A140A),
    isDark = false,
)

val DarkColors = CommuteColors(
    map = Color(0xFF0F291C),
    park = Color(0xFF1A4729),
    building = Color(0xFF1A4729),
    roadCasing = Color(0xFF08140D),
    road = Color(0xFF2E5238),
    roadMinor = Color(0xFF3A6248),
    route = Color(0xFF2D9E5A),
    dash = Color(0xFFB8D6BD),
    label = Color(0xFFB8D6BD),
    ink = Color(0xFFFCF9F1),
    muted = Color(0xFFB8D6BD),
    faint = Color(0xFFB8D6BD),
    surface = Color(0xFF122E21),
    handle = Color(0xFF474540),
    reason = Color(0xFFFDBC28),
    reasonOn = Color(0xFF0D5636),
    sample = Color(0xFF1A4729),
    sampleOn = Color(0xFFB8D6BD),
    para = Color(0xFFFCF9F1),
    paraOn = Color(0xFF0D5636),
    pinA = Color(0xFFF06020),
    pinAOn = Color(0xFFFCF9F1),
    pinB = Color(0xFFFCF9F1),
    pinBOn = Color(0xFF122E21),
    connector = Color(0xFF2E5238),
    step = Color(0xFF6BB375),
    shadow = Color(0x661A140A),
    isDark = true,
)

val LocalCommuteColors = staticCompositionLocalOf { LightColors }
